/*BASE ESQUELETO ALMUNDO MYSQL
@author Yaher Carrillo
@Date-Create 25/07/2018
@Date-last-change 25/07/2018
@Desciption:
EJECUTAR COMO SE MUESTRA A CONTINUACION*/

/*Crear base de datos*/
CREATE DATABASE almundo COLLATE 'utf8_general_ci';
/*Se toma la base de datos*/
use almundo;

/*Tablas maestro*/



/*Tabla de Usuarios del sistema.*/
CREATE TABLE almundo_usuarios (
	ID_USUARIO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(30) NOT NULL COLLATE 'utf8_general_ci',
	CLAVE VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_USUARIO VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	APELLIDO_USUARIO VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	EMAIL VARCHAR(30) COLLATE 'utf8_general_ci',
	SEXO VARCHAR(1) COLLATE 'utf8_general_ci',
	FECHA_REGISTRO DATE NOT NULL, 
	FECHA_ULTIMA_VIS DATE , 
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (ID_USUARIO),
	UNIQUE INDEX ID_USUARIO (ID_USUARIO),
	UNIQUE INDEX UK_LOGIN (LOGIN),
	UNIQUE INDEX UK_EMAIL (EMAIL),
	INDEX UDX_SEXO (SEXO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

/*Tabla de Perfiles del sistema.*/
CREATE TABLE almundo_perfiles (
	ID_PERFIL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	NOMBRE_PERFIL VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',	
	ADMINISTRADOR TINYINT(1) NOT NULL DEFAULT 0,	
	HABILITADO TINYINT(1) NOT NULL DEFAULT 0,	
	PRIMARY KEY (NOMBRE_PERFIL),
	UNIQUE INDEX ID_PERFIL (ID_PERFIL)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0
;

COMMIT;

/*Tabla de parametros del sistema*/
CREATE TABLE almundo_usuario_perfil (
	ID_USUARIO_PERFIL BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,	
	ID_USUARIO  BIGINT(20) UNSIGNED NOT NULL ,		
	ID_PERFIL  BIGINT(20) UNSIGNED NOT NULL ,		
	HABILITADO INT NOT NULL ,	
	PRIMARY KEY (ID_USUARIO,ID_PERFIL),	
	UNIQUE INDEX ID_USUARIO_PERFIL (ID_USUARIO_PERFIL),	      
   FOREIGN KEY (ID_PERFIL)
      REFERENCES almundo_perfiles(ID_PERFIL),
   FOREIGN KEY (ID_USUARIO)
      REFERENCES almundo_usuarios(ID_USUARIO)

)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

/*Tabla de parametros del sistema*/
CREATE TABLE almundo_parametros (
	ID_PARAMETRO BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	VALOR VARCHAR(256) NOT NULL COLLATE 'utf8_general_ci',
	TIPO_DATO VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE VARCHAR(128) NOT NULL COLLATE 'utf8_general_ci',
	GRUPO VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (ID_PARAMETRO),
	UNIQUE INDEX ID_PARAMETRO (ID_PARAMETRO),
	UNIQUE INDEX UK_NOMBRE_GRUPO (NOMBRE, GRUPO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE almundo_sala_llamadas (
	ID_SALA BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	ID_USUARIO BIGINT(20) UNSIGNED NOT NULL,
	HORA_INICIO DATE NOT NULL COLLATE 'utf8_general_ci',
	HORA_FIN DATE NOT NULL COLLATE 'utf8_general_ci',
	NOMBRE_SALA VARCHAR(128) NOT NULL COLLATE 'utf8_general_ci',
	ESTATUS_SALA VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (ID_SALA),
	UNIQUE INDEX ID_SALA (ID_SALA),
	FOREIGN KEY (ID_USUARIO)
      REFERENCES almundo_usuarios(ID_USUARIO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

CREATE TABLE almundo_sala_espera (
	ID_SALA_ATENCION BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	ID_USUARIO BIGINT(20) UNSIGNED NOT NULL,	
	ULTIMA_HORA_CONEC DATE NOT NULL COLLATE 'utf8_general_ci',	
	ESTATUS_USUARIO VARCHAR(64) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (ID_USUARIO),
	UNIQUE INDEX ID_SALA_ATENCION (ID_SALA_ATENCION),
	FOREIGN KEY (ID_USUARIO)
      REFERENCES almundo_usuarios(ID_USUARIO)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

commit;